nameOverride: ""
fullnameOverride: dns-controller-manager

replicaCount: 1

image:
  repository: eu.gcr.io/gardener-project/dns-controller-manager
  tag: v0.8.0-master
  pullPolicy: IfNotPresent

env: []

resources:
  requests:
   cpu: 100m
   memory: 64Mi
  limits:
   cpu: 200m
   memory: 128Mi

vpa:
  enabled: true
  minAllowed:
    cpu: 20m
    memory: 50Mi
  updatePolicy:
    updateMode: "Auto"

nodeSelector: {}
tolerations: []
affinity: {}
# priorityClassName: ""

createCRDs: true

#serviceAccountAnnotations:
#  annotkey1: annotvalue1
#  annotkey2: annotvalue2

configuration:
  # acceptedMaintainers: UNMANAGED
  # alicloudDNSRatelimiterBurst:
  # alicloudDNSRatelimiterEnabled:
  # alicloudDNSRatelimiterQps:
  # annotationDefaultPoolSize:
  # annotationPoolSize:
  # annotationSetup:
  # awsRoute53RatelimiterBurst:
  # awsRoute53RatelimiterEnabled:
  # awsRoute53RatelimiterQps:
  # azureDNSRatelimiterBurst:
  # azureDNSRatelimiterEnabled:
  # azureDNSRatelimiterQps:
  # bindAddressHttp:
  # cacheTtl: 120
  # cloudflareDNSRatelimiterBurst:
  # cloudflareDNSRatelimiterEnabled:
  # cloudflareDNSRatelimiterQps:
  # compoundAlicloudDnsRatelimiterBurst:
  # compoundAlicloudDnsRatelimiterEnabled:
  # compoundAlicloudDnsRatelimiterQps:
  # compoundAwsRoute53RatelimiterBurst:
  # compoundAwsRoute53RatelimiterEnabled:
  # compoundAwsRoute53RatelimiterQps:
  # compoundAzureDnsRatelimiterBurst:
  # compoundAzureDnsRatelimiterEnabled:
  # compoundAzureDnsRatelimiterQps:
  # compoundCacheDir:
  # compoundCacheTtl: 120
  # compoundCloudflareDnsRatelimiterBurst:
  # compoundCloudflareDnsRatelimiterEnabled:
  # compoundCloudflareDnsRatelimiterQps:
  # compoundDefaultPoolSize: 2
  # compoundDisableZoneStateCaching: false
  # compoundDnsClass: "gardendns"
  # compoundDnsDelay: 10s
  # compoundDnsPoolResyncPeriod: 30s
  # compoundDnsPoolSize: 1
  # compoundDryRun: false
  # compoundGoogleClouddnsRatelimiterBurst:
  # compoundGoogleClouddnsRatelimiterEnabled:
  # compoundGoogleClouddnsRatelimiterQps:
  # compoundIdentifier: ""
  # compoundInfobloxDnsRatelimiterBurst:
  # compoundInfobloxDnsRatelimiterEnabled:
  # compoundInfobloxDnsRatelimiterQps:
  # compoundOpenstackDesignateRatelimiterBurst:
  # compoundOpenstackDesignateRatelimiterEnabled:
  # compoundOpenstackDesignateRatelimiterQps:
  # compoundOwneridsPoolSize: 1
  # compoundPoolResyncPeriod:
  # compoundPoolSize:
  # compoundProviderTypes:
  # compoundProvidersPoolResyncPeriod: 30s
  # compoundProvidersPoolSize: 2
  # compoundRatelimiterBurst:
  # compoundRatelimiterEnabled:
  # compoundRatelimiterQps:
  # compoundRescheduleDelay: 120s
  # compoundSecretsPoolSize: 2
  # compoundSetup: 10
  # compoundStatisticPoolSize:
  # compoundTtl: 120
  # config:
  controllers: all
  # cpuprofile: ""
  # defaultPoolResyncPeriod:
  # defaultPoolSize:
  # disableNamespaceRestriction: false
  # disableZoneStateCaching: false
  # dnsClass: "gardendns"
  # dnsDelay: 10s
  # dnsTargetClass: ""
  # dnsPoolResyncPeriod: 30s
  # dnsPoolSize: 1
  # dnsentrySourceDefaultPoolResyncPeriod: 30s
  # dnsentrySourceDefaultPoolSize: 2
  # dnsentrySourceDnsClass: "gardendns"
  # dnsentrySourceDnsTargetClass: ""
  # dnsentrySourceExcludeDomains: google.com
  # dnsentrySourceKey: ""
  # dnsentrySourcePoolResyncPeriod:
  # dnsentrySourcePoolSize:
  # dnsentrySourceTargetCreatorLabelName: ""
  # dnsentrySourceTargetCreatorLabelValue: ""
  # dnsentrySourceTargetNamePrefix: ""
  # dnsentrySourceTargetNamespace: ""
  # dnsentrySourceTargetOwnerId: ""
  # dnsentrySourceTargetRealms: ""
  # dnsentrySourceTargetSetIgnoreOwners: false
  # dnsentrySourceTargetsPoolSize: 2
  # excludeDomains: google.com
  # forceCrdUpdate: false
  # googleCloudDNSRatelimiterBurst:
  # googleCloudDNSRatelimiterEnabled:
  # googleCloudDNSRatelimiterQps:
  # gracePeriod: 0
  # infobloxDNSRatelimiterBurst:
  # infobloxDNSRatelimiterEnabled:
  # infobloxDNSRatelimiterQps:
  # ingressDNSDefaultPoolResyncPeriod: 30s
  # ingressDNSDefaultPoolSize: 2
  # ingressDNSDnsClass: "gardendns"
  # ingressDNSDnsTargetClass: ""
  # ingressDNSExcludeDomains: google.com
  # ingressDNSKey: ""
  # ingressDNSPoolResyncPeriod:
  # ingressDNSPoolSize:
  # ingressDNSTargetCreatorLabelName: ""
  # ingressDNSTargetCreatorLabelValue: ""
  # ingressDNSTargetNamePrefix: ""
  # ingressDNSTargetNamespace: ""
  # ingressDNSTargetOwnerId: ""
  # ingressDNSTargetRealms: ""
  # ingressDNSTargetSetIgnoreOwners: false
  # ingressDNSTargetsPoolSize: 2
  # key: ""
  # kubeconfig: ""
  # kubeconfigDisableDeployCrds: false
  # kubeconfigId: ""
  # kubeconfigMigrationIds: ""
  # leaseDuration:
  # leaseName:
  # leaseRenewDeadline:
  # leaseRetryPeriod:
  # logLevel: info
  # maintainer:
  # namespace: default
  # namespaceLocalAccessOnly: false
  # omitLease: false
  # openstackDesignateRatelimiterBurst:
  # openstackDesignateRatelimiterEnabled:
  # openstackDesignateRatelimiterQps:
  # owneridsPoolSize:
  persistentCache: false
  persistentCacheStorageSize: 1Gi
  persistentCacheStorageSizeAlicloud: 20Gi
  # pluginFile:
  # poolResyncPeriod: 30s
  # poolSize: 2
  # providerTypes: ""
  # providers: ""
  # providersDisableDeployCrds: false
  # providersId: ""
  # providersMigrationIds: ""
  # providersPoolResyncPeriod: 30s
  # providersPoolSize: 1
  # ratelimiterBurst:
  # ratelimiterEnabled:
  # ratelimiterQps:
  # rescheduleDelay: 120s
  # secretsPoolSize:
  serverPortHttp: 8080
  # serviceDNSDefaultPoolResyncPeriod: 30s
  # serviceDNSDefaultPoolSize: 2
  # serviceDNSDnsClass: "gardendns"
  # serviceDNSDnsTargetClass: ""
  # serviceDNSExcludeDomains: google.com
  # serviceDNSKey: ""
  # serviceDNSPoolResyncPeriod:
  # serviceDNSPoolSize:
  # serviceDNSTargetCreatorLabelName: ""
  # serviceDNSTargetCreatorLabelValue: ""
  # serviceDNSTargetNamePrefix: ""
  # serviceDNSTargetNamespace: ""
  # serviceDNSTargetOwnerId: ""
  # serviceDNSTargetRealms: ""
  # serviceDNSTargetSetIgnoreOwners: false
  # serviceDNSTargetsPoolSize: 2
  # setup: 10
  # statisticPoolSize:
  # target: ""
  # targetCreatorLabelName: ""
  # targetCreatorLabelValue: ""
  # targetNamePrefix: ""
  # targetNamespace: ""
  # targetOwnerId: ""
  # targetRealms: ""
  # targetSetIgnoreOwners: false
  # targetDisableDeployCrds: false
  # targetId: ""
  # targetMigrationIds: ""
  # targetsPoolSize:
  ttl: 120
  # version:
additionalConfiguration: []

gardener:
  garden:
    identity: garden
  seed:
    identity: ""
    provider: ""

security:
  apparmorEnabled: false
  seccompEnabled: false
